FROM balenalib/%%BALENA_MACHINE_NAME%%-debian:bullseye

# Installiere ALSA
RUN install_packages alsa-utils

# ALSA Konfiguration
RUN echo 'pcm.!default {\n\
    type hw\n\
    card 0\n\
}\n\
\n\
ctl.!default {\n\
    type hw\n\
    card 0\n\
}' > /etc/asound.conf

# Kopiere Init-Script
COPY init-audio.sh /usr/local/bin/init-audio.sh
RUN chmod +x /usr/local/bin/init-audio.sh

CMD ["/usr/local/bin/init-audio.sh"]
